
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
  database: smartspace_test_task_production
  password: <%= ENV['SMARTSPACE_TEST_TASK_DATABASE_PASSWORD'] %>
